FROM python:3.9-buster

ENV PORT 5000

WORKDIR /app
COPY ./scripts ./scripts
COPY ./requirements.txt .
COPY ./makefile .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y make
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN bash -c "make set_up"
RUN bash -c "make authtoken"

COPY . .
Run bash -c "make fetch_model"

EXPOSE $PORT

CMD ["make", "run"]